# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GJiRU0LZmncQZCry0a4tErQCQFera2Du
"""

import streamlit as st
import csv
import os
from datetime import datetime

# Person_Info class
class Person_Info:
    def __init__(self, name, age, gender, mail, Date, tall, weight, fitness_goal, activity_level, body_fat_percentage, muscle_percentage, water_percentage):
        self.name = name
        self.age = age
        self.gender = gender
        self.mail = mail
        self.Date = Date
        self.tall = tall
        self.weight = weight
        self.fitness_goal = fitness_goal
        self.activity_level = activity_level
        self.body_fat_percentage = body_fat_percentage
        self.muscle_percentage = muscle_percentage
        self.water_percentage = water_percentage

    def save_to_csv(self, filename="person_data.csv"):
        file_exists = os.path.isfile(filename)
        with open(filename, mode='a', newline='', encoding='utf-8') as file:
            writer = csv.writer(file)
            if not file_exists:
                writer.writerow([
                    "Name", "Age", "Gender", "Mail", "Date", "Tall", "Weight",
                    "Fitness Goal", "Activity Level", "Body Fat %",
                    "Muscle %", "Water %"
                ])
            writer.writerow([
                self.name, self.age, self.gender, self.mail, self.Date, self.tall, self.weight,
                self.fitness_goal, self.activity_level, self.body_fat_percentage,
                self.muscle_percentage, self.water_percentage
            ])

# Trainer_Info class
class Trainer_Info:
    def __init__(self, trainer_name, trainer_age, trainer_gender, trainer_mail, specialization, experience_years):
        self.trainer_name = trainer_name
        self.trainer_age = trainer_age
        self.trainer_gender = trainer_gender
        self.trainer_mail = trainer_mail
        self.specialization = specialization
        self.experience_years = experience_years

    def save_to_csv(self, filename="trainer_data.csv"):
        file_exists = os.path.isfile(filename)
        with open(filename, mode='a', newline='', encoding='utf-8') as file:
            writer = csv.writer(file)
            if not file_exists:
                writer.writerow([
                    "Name", "Age", "Gender", "Mail", "Specialization", "Experience Years"
                ])
            writer.writerow([
                self.trainer_name, self.trainer_age, self.trainer_gender, self.trainer_mail, self.specialization, self.experience_years
            ])

# Streamlit UI
st.title("🏋️‍♂️ Fitness & Trainer Data App")

menu = ["Person Info", "Trainer Info"]
choice = st.sidebar.selectbox("Select Option", menu)

if choice == "Person Info":
    st.header("Enter Person Info")
    name = st.text_input("Name")
    age = st.number_input("Age", min_value=0)
    gender = st.selectbox("Gender", ["Male", "Female"])
    mail = st.text_input("Email")
    tall = st.number_input("Height (cm)", min_value=0.0)
    weight = st.number_input("Weight (kg)", min_value=0.0)
    fitness_goal = st.text_input("Fitness Goal")
    activity_level = st.text_input("Activity Level")
    body_fat_percentage = st.number_input("Body Fat %", min_value=0.0)
    muscle_percentage = st.number_input("Muscle %", min_value=0.0)
    water_percentage = st.number_input("Water %", min_value=0.0)

    if st.button("Save Person Data"):
        date_now = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        person = Person_Info(name, age, gender, mail, date_now, tall, weight, fitness_goal, activity_level, body_fat_percentage, muscle_percentage, water_percentage)
        person.save_to_csv()
        st.success("✅ Person Data Saved Successfully!")

elif choice == "Trainer Info":
    st.header("Enter Trainer Info")
    name = st.text_input("Trainer Name")
    age = st.number_input("Trainer Age", min_value=0)
    gender = st.selectbox("Trainer Gender", ["Male", "Female"])
    mail = st.text_input("Trainer Email")
    specialization = st.text_input("Specialization")
    experience_years = st.number_input("Experience Years", min_value=0)

    if st.button("Save Trainer Data"):
        trainer = Trainer_Info(name, age, gender, mail, specialization, experience_years)
        trainer.save_to_csv()
        st.success("✅ Trainer Data Saved Successfully!")